# Generated by Django 5.1.4 on 2025-03-26 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_remove_busstation_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="busstation",
            name="contact_number",
        ),
    ]
