# Generated by Django 5.1.4 on 2025-03-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_alter_busstation_province"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="bus_type",
            field=models.CharField(
                choices=[
                    ("Sitting", "Ngồi"),
                    ("Sleeper", "Giường nằm"),
                    ("SleeperVIP", "Giường nằm VIP"),
                ],
                max_length=10,
            ),
        ),
    ]
