# Generated by Django 5.1.4 on 2025-03-27 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_alter_bus_bus_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seat",
            name="seat_type",
        ),
        migrations.AddField(
            model_name="bus",
            name="surcharge",
            field=models.IntegerField(
                choices=[(0, 0), (50, 50), (100, 100)], default=0
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="base_price",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="SeatTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Còn trống"),
                            ("Booked", "Đã đặt"),
                            ("InProgress", "Đang tiến hành"),
                        ],
                        default="Available",
                        max_length=15,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booking.seat"
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booking.trip"
                    ),
                ),
            ],
            options={
                "unique_together": {("trip", "seat")},
            },
        ),
        migrations.DeleteModel(
            name="PriceList",
        ),
    ]
